FROM node:20-slim AS base
WORKDIR /app
RUN corepack enable
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

FROM base AS deps
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/worker/package.json apps/worker/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN pnpm install

FROM deps AS builder
COPY apps/worker apps/worker
COPY packages/db packages/db
COPY packages/shared packages/shared
RUN pnpm --filter @app/db generate
RUN pnpm --filter @app/shared build
RUN pnpm --filter @app/db build
RUN pnpm --filter @app/worker build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/apps/worker ./apps/worker
COPY --from=builder /app/packages ./packages
RUN pnpm --filter @app/db generate
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=builder /app/tsconfig.base.json ./tsconfig.base.json
CMD ["pnpm", "--filter", "@app/worker", "start"]
